// examples/react-hero-example/src/HeroDetail/HeroDetail.js
import React, { Component } from 'react';

class HeroDetail extends Component {
  render() {
    return (
      <div className="container">
        <h1> Details </h1>
        <p>Name: { this.props.hero.name }</p>
        <p>Type: { this.props.hero.type }</p>
        <p>Health: { this.props.hero.health }</p>
        <p>Mana: { this.props.hero.mana }</p>
        <p>Damage: { this.props.hero.dmg }</p>
      </div>
    );
  }
}

export default HeroDetail;

// examples/ng2-hero-example/src/app/hero-detail/hero-detail.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Hero } from '../models/hero';
import { HeroService } from '../services/hero.service';

@Component({
  selector: 'app-hero-detail',
  templateUrl: './hero-detail.component.html',
  styleUrls: ['./hero-detail.component.css']
})
export class HeroDetailComponent implements OnInit {

  @Input() hero: Hero;
  title: string;

  constructor() { }

  ngOnInit() {
    this.title = "Hero Details";
  }
}

<div>
    <h1> {{ title }} </h1>
  <p id="name">Name: {{ hero.name }}</p>
  <p id="type">Type: {{ hero.type }}</p>
  <p id="health">Health: {{ hero.health }}</p>
  <p id="mana">Mana: {{ hero.mana }}</p>
  <p id="dmg">Damage: {{ hero.dmg }}</p>
</div>
