// examples/react-hero-example/src/NewHeroForm/NewHeroForm.js
import React, { Component } from 'react';

import Input from '../Input/Input';
import Hero from '../models/hero';

class NewHeroForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      hero: new Hero('', '', 0, 0, 0)
    };
  }
  render() {
    return (
      <div>
        <h1>Add New Hero</h1>
        <form className="form-inline">
          <Input handleInputChange={ this.handleInputChange } type="text" name="name" />
          <Input handleInputChange={ this.handleInputChange } type="text" name="type" />
          <Input handleInputChange={ this.handleInputChange } type="number" name="health" />
          <Input handleInputChange={ this.handleInputChange } type="number" name="mana" />
          <Input handleInputChange={ this.handleInputChange } type="number" name="damage" />
          <button onClick={ () => this.props.addHero(this.state.hero) } className="btn btn-default" type="button">Add Hero</button>
        </form>
      </div>
    );
  }
  handleInputChange = (key, value) => {
    let hero = this.state.hero;
    hero[key] = value;
    this.setState({
      hero: hero
    });
  }
}

export default NewHeroForm;

// examples/ng2-hero-example/src/app/new-hero-form/new-hero-form.component.ts
import { Component, OnInit } from '@angular/core';

import { Hero } from '../models/hero';
import { HeroService } from '../services/hero.service';

@Component({
  selector: 'app-new-hero-form',
  templateUrl: './new-hero-form.component.html',
  styleUrls: ['./new-hero-form.component.css']
})
export class NewHeroFormComponent implements OnInit {
  title: string;
  name: string;
  type: string;
  health: number;
  mana: number;
  dmg: number;

  constructor(private heroService: HeroService) { }

  ngOnInit() {
    this.title = "New Hero";
  }

  createHero() {
    const hero = new Hero(this.name, this.type, this.health, this.mana, this.dmg);
    this.heroService.addHero(hero);
  }
}

<h1> {{ title }} </h1>
<form class="form-inline">
  <div class="form-group">
    <input [(ngModel)]="name" type="text" name="name" class="form-control" placeholder="Name">
  </div>
  <div class="form-group">
    <input [(ngModel)]="type" type="text" name="type" class="form-control" placeholder="Type">
  </div>
  <div class="form-group">
    <input [(ngModel)]="health" type="number" name="health" class="form-control" placeholder="Health">
  </div>
  <div class="form-group">
    <input [(ngModel)]="mana" type="number" name="mana" class="form-control" placeholder="Mana">
  </div>
  <div class="form-group">
    <input [(ngModel)]="dmg" type="number" name="damage" class="form-control" placeholder="Damage">
  </div>
  <button (click)="createHero()" class="btn btn-default">Create Hero</button>
</form>
